<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsDesktopSDK>true</UseWindowsDesktopSDK>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFE.Core\SFE.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

</Project>
